export const games = [
  [1, 'Red'],
  [2, 'Blue'],
  [3, 'Yellow'],
  [4, 'Gold'],
  [5, 'Silver'],
  [6, 'Crystal'],
  [7, 'Ruby'],
  [8, 'Sapphire'],
  [9, 'Emerald'],
  [10, 'Fire Red'],
  [11, 'Leaf Green'],
  [12, 'Diamond'],
  [13, 'Pearl'],
  [14, 'Platinum'],
  [15, 'Heart Gold'],
  [16, 'Soul Silver'],
  [17, 'Black'],
  [18, 'White'],
  [19, 'Black 2'],
  [20, 'White 2'], 
  [21, 'X'],
  [22, 'Y'],
  [23, 'Omega Ruby'],
  [24, 'Alpha Saphire'],
  [25, 'Sun'],
  [26, 'Moon'],
  [27, 'Ultra Sun'],
  [28, 'Ultra Moon'],
  [29, 'Sword'], 
  [30, 'Shield'], 
  [31, 'Brilliant Diamond'],
  [32, 'Shining Pearl'],
  [33, 'Legends: Arceus'],
  [34, 'Scarlet'],
  [35, 'Violet']
]